repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-toml
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: trailing-whitespace


-   repo: https://github.com/psf/black
    rev: '23.1.0'
    hooks:
      - id: black
        args: [
          --config=pyproject.toml,
        ]

-   repo: https://github.com/adamchainz/blacken-docs
    rev: '1.13.0'
    hooks:
      - id: blacken-docs
        args: [
           --line-length=88
        ]

-   repo: https://github.com/PyCQA/docformatter
    rev: 'v1.5.0'
    hooks:
      - id: docformatter
        args: [
          --config=pyproject.toml,
        ]

-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.247'
    hooks:
      - id: ruff
        args: [
          --fix,
          --show-fixes
        ]
-   repo: local
    hooks:
      - id: pytest
        language: python
        name: pytest
        entry: pytest
        always_run: true
        pass_filenames: false
        stages: [push]
        verbose: true
        args: [
          --cov=moorpy,
          --cov-report=xml,
          ./tests,
        ]
